{{- if .Values.config.securityBasicAuthEnable -}}                    
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "psi-todo.fullname" . }}-secret
  labels:
    app: {{ include "psi-todo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  security-basic-auth-username: {{ .Values.security.basicAuth.username | required "Basic-Auth username is required" | b64enc }}
  security-basic-auth-password: {{ .Values.security.basicAuth.password | required "Basic-Auth password is required" | b64enc }}
{{end}}  