apiVersion: v1
kind: Service
metadata:
  name: {{ include "psi-todo.fullname" . }}
  labels:
    {{- include "psi-todo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    {{- include "psi-todo.selectorLabels" . | nindent 4 }}
