image:
  repository: "ghcr.io/raghav2211/spring-web-flux-todo-app/maven/config-server"
  tag: "1.0.0"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube