#Default values fo Config server
replica: 1
image:
  repository: config-server
  pullPolicy: IfNotPresent
  tag: "1.0.0"


livenessProbe: {}
#  enabled: false
#  initialDelaySeconds: 60
#  periodSeconds: 30
#  timeoutSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3

service:
  type: LoadBalancer
  port:
    to: 8888
    from: 8080
  nodePort: 30002

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

affinity: {}