version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.21
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
  kms:
    container_name: kms
    image: nsmithuk/local-kms:3.11.2
    volumes:
      - ./env/local/kms:/init
    ports:
      - 4566:8080
      - 4599:8080

  config-server:
    image: config-server:${CONFIG_SERVER_IMAGE_TAG}
    container_name: config-server

  todo:
    image: todo:${TODO_IMAGE_TAG}
    container_name: todo
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AWS_ACCESS_KEY: dummy
      AWS_SECRET_ACCESS_KEY: dummy

  edge-service:
    image: edge-service:${EDGE_SERVICE_IMAGE_TAG}
    container_name: edge-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AWS_ACCESS_KEY: dummy
      AWS_SECRET_ACCESS_KEY: dummy
