version: "3.9"
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2.21
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: tododb
    ports:
      - "27017:27017"
    volumes:
      - ./env/local/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
  kms:
    container_name: kms
    image: nsmithuk/local-kms:3.11.2
    volumes:
      - ./env/local/kms:/init
    ports:
      - 4566:8080
      - 4599:8080

  config-server:
    image: config-server:${CONFIG_SERVER_IMAGE_TAG}
    container_name: config-server
    depends_on:
      - kms

  todo:
    image: todo:${TODO_IMAGE_TAG}
    container_name: todo
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - config-server
      - edge-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      AWS_ACCESS_KEY: dummy
      AWS_SECRET_ACCESS_KEY: dummy

  edge-service:
    image: edge-service:${EDGE_SERVICE_IMAGE_TAG}
    container_name: edge-service
    ports:
      - "8081:8080"
    depends_on:
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: local
      AWS_ACCESS_KEY: dummy
      AWS_SECRET_ACCESS_KEY: dummy
