version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.21
    ports:
      - "27017:27017"
  kms:
    container_name: kms
    image: nsmithuk/local-kms:3.11.2
    volumes:
      - ./env/local/kms:/init
    ports:
      - 4566:8080
      - 4599:8080
  todo:
    image: todo:${TODO_IMAGE_TAG}
    container_name: todo
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
  edge-service:
    image: edge-service:${EDGE_SERVICE_IMAGE_TAG}
    container_name: edge-service
    ports:
      - "8081:8081"
    environment:
      CLIENT_SECRET: ${EDGE_GOOGLE_CLIENT_SECRET}
      CLIENT_ID: ${EDGE_GOOGLE_CLIENT_ID}
      SPRING_PROFILES_ACTIVE: docker
