version: "3.9"
services:
  mongodb:
    container_name: mongo
    image: mongo:4.2.21
    ports:
      - "27017:27017"
  todo:
    image: todo:2.0.0
    container_name: todo
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongo

  edge-service:
    image: edge-service:1.0.0
    container_name: edge-service
    ports:
      - "8081:8081"
    environment:
      CLIENT_SECRET: "<client-secret>"
      CLIENT_ID: "<client-id>"
      TODO_APP_HOST: todo
