version: "3.9"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  todo:
    image: ghcr.io/raghav2211/spring-web-flux-todo-app/todo:${TODO_IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql:3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DATABASE}
      TODO_SECURITY_BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      TODO_SECURITY_BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
