version: "3.9"
services:
  mongodb:
    deploy:
      labels:
        name: mongodb
        component: database
        env: "local"
      placement: 
        constraints: 
          - "node.role == worker"
  kms:
    deploy:
      labels:
        name: kms
        version: latest
        component: security
        env: "local"
      replicas: 1
      placement:
        constraints:
          - "node.role == worker"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  todo:
    image: ${TODO_STACK_IMAGE}
    deploy:
      labels:
        name: todo
        version: latest
        component: web
        env: "local" 
      replicas: ${TODO_REPLICA}
      placement: 
        constraints: 
          - "node.role == worker" 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  edge-service:
    image: ${EDGE_SERVICE_STACK_IMAGE}
    deploy:
      labels:
        name: edge-service
        version: latest
        component: web
        env: "local"
      replicas: ${EDGE_SERVICE_REPLICA}
      placement:
        constraints:
          - "node.role == worker"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  config-server:
    image: ${CONFIG_SERVER_STACK_IMAGE_TAG}
    deploy:
      labels:
        name: config-server
        version: latest
        component: security
        env: "local"
      replicas: ${CONFIG_SERVER_REPLICA}
      placement:
        constraints:
          - "node.role == worker"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5