image:
  repository: "ghcr.io/raghav2211/spring-web-flux-todo-app/maven/edge-service"

springProfiles: ci

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube