#Default values fo mysql
replicaCount: 1
image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: "8.0.22"

service:
  type: ClusterIP
  port: 3306  

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#persistence is to recover data after pod kill
persistence: {}
  #local: false
  #storageClass: local 
  #accessMode: 
  #  - ReadWriteOnce
  #size: 1Gi
  #hostPath: /mnt/data

#mysqlConfig :- Configuration for mysql
#required url & database
mysqlConfig:
  database: klab

# affinityNodes is the nodes list in which pod will deploy
# default - minikube
affinityNodes: []