{{- if .Values.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "mysql.fullname" . }}-pv
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    {{- range .Values.persistence.accessMode }}
        - {{ . }}
    {{end}}        
  capacity:
      storage: {{ .Values.persistence.size }}
{{- if .Values.persistence.local }}      
  hostPath:
    path: {{ .Values.persistence.hostPath | required "Host path is required" | quote }}
{{end}}
  {{- if .Values.nodeAffinity }}    
  nodeAffinity:
  {{- end }}
  {{- with .Values.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution }}
    required:
{{ toYaml . | indent 10 }}
      {{- end }}                              
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mysql.fullname" . }}-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  accessModes:
    {{- range .Values.persistence.accessMode }}
        - {{ . }}
    {{end}}  
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }} 
{{end}}                