apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.fullname" . }}-secret
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  username: {{ .Values.mysqlUsername | required "Mysql username is required" }}
  password: {{ .Values.mysqlPassword | required "Mysql password is required" }}