#Default values fo Todo app
replica: 1
image:
  repository: edge-service
  pullPolicy: Always
  tag: "1.0.0"


livenessProbe: {}
#  enabled: false
#  initialDelaySeconds: 60
#  periodSeconds: 30
#  timeoutSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3

service:
  type: LoadBalancer
  port: 8081
  nodePort: 30001

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# edge - oauth2 secrets
edge: {}
#  google:
#    clientId:
#    clientSecret:

springProfiles: k8s

ingress:
  enabled: false