#Default values fo Edge Service
replica: 1
image:
  repository: edge-service
  pullPolicy: IfNotPresent
  tag: "1.0.0"


livenessProbe: {}
#  enabled: false
#  initialDelaySeconds: 60
#  periodSeconds: 30
#  timeoutSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3

service:
  type: LoadBalancer
  port: 8081
  nodePort: 30001

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

springProfiles: k8s

affinity: {}

ingress:
  enabled: false

redis:
  enabled: true
  fullnameOverride: redis
  master:
    kind: Deployment
  architecture: standalone
  persistence:
    enabled: false
  serviceAccount:
    create: false
  auth:
    enabled: false