#Default values fo Todo app
replicaCount: 1
image:
  repository: klab-todo
  pullPolicy: Never
  tag: "0.0.1"


livenessProbe:
  enabled: false
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3

service:
  type: LoadBalancer
  port: 8080
  nodePort: 30000

#mysqlRef is for inject secret & config of mysql
mysqlRef: "" 

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

initContainers:
  dbWait: # dbWait until mysql is not up 
    image: busybox 
    tag: latest
    imagePullPolicy: IfNotPresent  