apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}
  labels: {{- include "todo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replica | default 1 }}
  selector:
    matchLabels:
      {{- include "todo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 - key: kubernetes.io/hostname
                   operator: In
                   values:
{{- if .Values.affinityNodes -}}                    
                   {{- range .Values.affinityNodes }}
                     - {{ . }}
                   {{- end }}
{{else}}
                     - {{ default "minikube" }}
{{end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default .Chart.Name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}    
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: {{ default 60 .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 30 .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ default 10 .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ default 1 .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ default 3 .Values.livenessProbe.failureThreshold }}
          {{end}}  
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfiles }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}