version: "3"
services:
  psimysql:
    image: mysql:8.0.22
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: psi
      MYSQL_ROOT_PASSWORD: root
  psitodoapp:
    image: psi-todo:0.0.1
    container_name: psi-todo
    restart: on-failure:5 
    depends_on:
      - psimysql
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: psimysql:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB_NAME: psi
      # UnComment below 3 properties to enable basic auth security
      #PSI_TODO_SECURITY_BASIC_AUTH_ENABLE: "true"
      #PSI_TODO_SECURITY_BASIC_AUTH_USERNAME: "admin"
      #PSI_TODO_SECURITY_BASIC_AUTH_PASSWORD: "{noop}password"