version: "3"
services:
  psimysql:
    image: mysql:${MYSQL_IMAGE_TAG:-8.0.22}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  psitodoapp:
    image: psi-todo:${PSI_TODO_IMAGE_TAG:-latest}
    depends_on:
      - psimysql # will not wait for mysql to be “ready” before starting todo-app , It'll only confirm dependency order & 
                 # will automatic create dependencies which include in service defination
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: psimysql:3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DATABASE}
      # UnComment below 3 properties to enable basic auth security
      #PSI_TODO_SECURITY_BASIC_AUTH_ENABLE: ${BASIC_AUTH_ENABLE}
      #PSI_TODO_SECURITY_BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      #PSI_TODO_SECURITY_BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}