apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      {{- if eq .Values.service.type "LoadBalancer" }}
      nodePort: {{ .Values.service.nodePort }}
      {{end}}
      name: http
  selector:
    {{- include "config-server.selectorLabels" . | nindent 4 }}
