image:
  repository: "{{ .Values.aws.account }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/edge-service"

springProfiles: eks

affinity: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  class: nginx
  hostname: edge-service.todo.tmp.dev.farm
