apiVersion: v2
name: todo
description: A Helm chart for Todo Rest API
type: application
version: 2.0.0
appVersion: 2.0.0
dependencies:
  - name: mongodb
    version: 12.1.24
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
