#Default values fo Todo app
replica: 1
image:
  repository: todo
  pullPolicy: IfNotPresent
  tag: "2.0.0"


livenessProbe: {}
#  enabled: false
#  initialDelaySeconds: 60
#  periodSeconds: 30
#  timeoutSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3

service:
  type: LoadBalancer
  port: 8080
  nodePort: 30000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

springProfiles: local

#mongo chart values
mongodb:
  persistence:
    enabled: false
  enabled: true
  fullnameOverride: mongodb
  auth:
    enabled: true
    rootPassword: pass
    usernames:
      - admin
    passwords:
      - pass
    databases:
      - tododb

affinity: {}

ingress:
  enabled: false