apiVersion: apps/v1
kind: Deployment
metadata:
  name: klab-todo
  labels:
    app: klab-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klab-todo
  template:
    metadata:
      labels:
        app: klab-todo
    spec:
      containers:
        - name: klab-todo
          image: klab-todo:0.0.1
          imagePullPolicy: Never
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: klabtodo
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: klabtodo
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 10
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: mysql-config
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mysql-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secret
            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: database
                  name: mysql-config
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: todo-secret
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: todo-secret
      initContainers:
        - name: init-mysql
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup mysql; do echo waiting for mysql; sleep 2; done;",
            ]

---
apiVersion: v1
kind: Service
metadata:
  name: klab-todo
spec:
  selector:
    app: klab-todo
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
