image:
  repository: "{{ .Values.aws.account }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/todo"

springProfiles: eks

affinity: {}

service:
  type: ClusterIP

mongodb:
  enabled: false

ingress:
  enabled: true
  class: nginx
  hostname: todo-app.todo.tmp.dev.farm