nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values:
             - minikube

persistence:
  enabled: true
  local: true
  storageClass: local 
  accessMode: 
    - ReadWriteOnce
  size: 1Gi
  hostPath: /mnt/data