name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo-app

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # Step that does that actual cache save and restore
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build with Maven
      run: mvn -B package
    - name: Build local image
      run: |
        docker build --tag psi-todo .
        docker build --build-arg JAR_FILE=build/libs/\*.jar --tag psi-todo .
    - name: Build local stack
      run: docker-compose --env-file=env/ci/Docker.env up -d
    - name: Test local stack
      run: |
        sleep 120
        docker run --network container:psi-todo appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/actuator/health
