name: K8s Deployment validate

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'helm-charts/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'helm-charts/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: build & validate helm-charts in minikube
    steps:
      - uses: actions/checkout@v2
      - name: Helm lint
        run: |
          helm lint helm-charts/todo
          helm lint helm-charts/edge-service
          helm lint helm-charts/config-server
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Deploy local kms
        run: kubectl create -f k8s/local-kms.yml
      - name: Try the cluster !
        run: kubectl get pods -A