name: "Terraform Check"

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.tf'
      - '!**/README.md'
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - '**.tf'
      - '!**/README.md'

jobs:
  terraform-validate:
    name: "tf validate"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.2
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: "Terraform Format check"
        run: |
          find . \( -path '*/.terraform/*' \) -prune -false -o -type f -name '*.tf' | while read f
          do
            terraform fmt -check $f
              if [ $? -ne 0 ]
              then
                  exit 1;
              fi
          done

      - name: "Terraform Init & Validate"
        env:
          AWS_DEFAULT_REGION: us-east-2
        run: |
          terraform -chdir=remote-state/lab/us-east-2 init -backend=false
          terraform -chdir=remote-state/lab/us-east-2 validate

          terraform -chdir=lab/us-east-2/dev/vpc init -backend=false
          terraform -chdir=lab/us-east-2/dev/vpc validate

          terraform -chdir=lab/us-east-2/dev/apps/todo/v2/ecr init -backend=false
          terraform -chdir=lab/us-east-2/dev/apps/todo/v2/ecr validate

          terraform -chdir=lab/us-east-2/dev/apps/todo/v2/mongo init -backend=false
          terraform -chdir=lab/us-east-2/dev/apps/todo/v2/mongo validate

          terraform -chdir=lab/us-east-2/dev/apps/todo/v2/redis init -backend=false
          terraform -chdir=lab/us-east-2/dev/apps/todo/v2/redis validate

          terraform -chdir=lab/us-east-2/dev/apps/todo/v2/kms init -backend=false
          terraform -chdir=lab/us-east-2/dev/apps/todo/v2/kms validate

          terraform -chdir=lab/us-east-2/dev/eks/cluster init -backend=false
          terraform -chdir=lab/us-east-2/dev/eks/cluster validate

          terraform -chdir=lab/us-east-2/dev/apps/todo/v1 init -backend=false
          terraform -chdir=lab/us-east-2/dev/apps/todo/v1 validate

          terraform -chdir=lab/global/route53 init -backend=false
          terraform -chdir=lab/global/route53 validate

          terraform -chdir=lab/us-east-2/dev/eks/services/external-dns init -backend=false
          terraform -chdir=lab/us-east-2/dev/eks/services/external-dns validate

          terraform -chdir=lab/us-east-2/dev/eks/services/ingress-nginx init -backend=false
          terraform -chdir=lab/us-east-2/dev/eks/services/ingress-nginx validate